# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Compendium TU
author: Daniel Steinmaurer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:  
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    - html_admonition
    # - html_image
    - linkify
    # - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_dmath_double_inline: true 

# Information about where the book exists on the web
# Add GitHub buttons to your book
repository:
  url: https://github.com/Dan00712/Compendium_TU
