name: Build and Publish PDF Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Use the version you need

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter-book
      working-directory: ${{ github.workspace }}

    - name: Build PDF
      run: jupyter-book build . --builder pdflatex
      working-directory: ${{ github.workspace }}

    - name: Create PDF Release
      run: |
        mv _build/pdf/book.pdf book.pdf
        git config user.email "you@example.com"
        git config user.name "Your Name"
        git add book.pdf
        git commit -m "Add PDF release"
        git push
      working-directory: ${{ github.workspace }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: book.pdf
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload PDF to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: book.pdf
        asset_name: book.pdf
        asset_content_type: application/pdf
